name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/public
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: kingOfHH.jar                 #.jar must be the same as 'finalName' in pom.xml
          path: backend/target/kingOfHH.jar  #.jar must be the same as 'finalName' in pom.xml

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:                              #optional, only shows link in RepoPage
      name: king-of-hh-heroku                   #change environment name as you like
      url: https://king-of-hh.herokuapp.com/ #change to your App-URL provided by heroku

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: kingOfHH.jar                  #.jar must be the same as 'finalName' in pom.xml
          path: backend/target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a king-of-hh      #Change with your heroku-app name
      - name: Deploy docker container
        run: heroku container:release web -a king-of-hh   #Change with your heroku-app name

